name: Publish firmware

on:
 workflow_dispatch:


jobs:

  # Publish code

  publish:

    runs-on: macos-latest
    
    steps:

      # Clone repository
      
      - name: Clone repository
        uses: actions/checkout@main

      # Setup arduino CLI
      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      # Configure platform
      
      - name: Configure platform
        run: |
          arduino-cli config init 
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install --git-url https://github.com/me-no-dev/ESPAsyncWebServer.git https://github.com/me-no-dev/ESPAsyncTCP.git
          
      # Compile
      
      - name: Compile sketch
        run: |
          arduino-cli compile -b "esp8266:esp8266:nodemcuv2" -e ./sketch

      # Upload to artifacts

      - name: Upload to artifacts
        uses: actions/upload-artifact@main
        with:
          name: firmware.bin
          path: ./sketch/build/*.*.*/*.ino.bin

      # Remove old firmware folder & update version file

      - name: Remove old firmwares
        run: |
          rm -rf ./updater/firmware.bin || true
          rm -rf ./updater/version-check.txt || true
          cp ./sketch/build/*.*.*/*.ino.bin ./updater/firmware.bin
          cp ./sketch/version.txt ./updater/version-check.txt
          rm -rf ./sketch/build

      # Read version file

      - name: Read version file
        id: version
        uses: juliangruber/read-file-action@master
        with:
          path: ./sketch/version.txt

      # Update repository

      - name: Push firmwares to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "🏗️ Build v${{steps.version.outputs.content}}" || true
          git push || true

      # Publish release

      - name: Publish release
        uses: ncipollo/release-action@main
        with:
          tag: ${{ steps.version.outputs.content }}
          name: Release v${{ steps.version.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: release.md
          artifacts: ./updater/firmware.bin